/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportRouteImport } from './routes/report'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiDistanceRouteImport } from './routes/api/distance'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiFormatAddressRouteImport } from './routes/api/format/address'
import { Route as ApiGeofenceCheckRouteImport } from './routes/api/geofence/check'
import { Route as ApiPublicBulkZipRouteImport } from './routes/api/public/bulk-zip'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiShippingEstimateRouteImport } from './routes/api/shipping/estimate'
import { Route as ApiTravelVisaRequirementsRouteImport } from './routes/api/travel/visa-requirements'
import { Route as ApiUtilsAnonymizeRouteImport } from './routes/api/utils/anonymize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDistanceRoute = ApiDistanceRouteImport.update({
  id: '/api/distance',
  path: '/api/distance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormatAddressRoute = ApiFormatAddressRouteImport.update({
  id: '/api/format/address',
  path: '/api/format/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeofenceCheckRoute = ApiGeofenceCheckRouteImport.update({
  id: '/api/geofence/check',
  path: '/api/geofence/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBulkZipRoute = ApiPublicBulkZipRouteImport.update({
  id: '/api/public/bulk-zip',
  path: '/api/public/bulk-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingEstimateRoute = ApiShippingEstimateRouteImport.update({
  id: '/api/shipping/estimate',
  path: '/api/shipping/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelVisaRequirementsRoute =
  ApiTravelVisaRequirementsRouteImport.update({
    id: '/api/travel/visa-requirements',
    path: '/api/travel/visa-requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUtilsAnonymizeRoute = ApiUtilsAnonymizeRouteImport.update({
  id: '/api/utils/anonymize',
  path: '/api/utils/anonymize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/status': typeof StatusRoute
  '/vote': typeof VoteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/distance': typeof ApiDistanceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/format/address': typeof ApiFormatAddressRoute
  '/api/geofence/check': typeof ApiGeofenceCheckRoute
  '/api/public/bulk-zip': typeof ApiPublicBulkZipRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/shipping/estimate': typeof ApiShippingEstimateRoute
  '/api/travel/visa-requirements': typeof ApiTravelVisaRequirementsRoute
  '/api/utils/anonymize': typeof ApiUtilsAnonymizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/status': typeof StatusRoute
  '/vote': typeof VoteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/distance': typeof ApiDistanceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/format/address': typeof ApiFormatAddressRoute
  '/api/geofence/check': typeof ApiGeofenceCheckRoute
  '/api/public/bulk-zip': typeof ApiPublicBulkZipRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/shipping/estimate': typeof ApiShippingEstimateRoute
  '/api/travel/visa-requirements': typeof ApiTravelVisaRequirementsRoute
  '/api/utils/anonymize': typeof ApiUtilsAnonymizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/status': typeof StatusRoute
  '/vote': typeof VoteRoute
  '/api/$': typeof ApiSplatRoute
  '/api/distance': typeof ApiDistanceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/format/address': typeof ApiFormatAddressRoute
  '/api/geofence/check': typeof ApiGeofenceCheckRoute
  '/api/public/bulk-zip': typeof ApiPublicBulkZipRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/shipping/estimate': typeof ApiShippingEstimateRoute
  '/api/travel/visa-requirements': typeof ApiTravelVisaRequirementsRoute
  '/api/utils/anonymize': typeof ApiUtilsAnonymizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/report'
    | '/status'
    | '/vote'
    | '/api/$'
    | '/api/distance'
    | '/api/search'
    | '/api/format/address'
    | '/api/geofence/check'
    | '/api/public/bulk-zip'
    | '/api/public/stats'
    | '/api/shipping/estimate'
    | '/api/travel/visa-requirements'
    | '/api/utils/anonymize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/report'
    | '/status'
    | '/vote'
    | '/api/$'
    | '/api/distance'
    | '/api/search'
    | '/api/format/address'
    | '/api/geofence/check'
    | '/api/public/bulk-zip'
    | '/api/public/stats'
    | '/api/shipping/estimate'
    | '/api/travel/visa-requirements'
    | '/api/utils/anonymize'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/map'
    | '/report'
    | '/status'
    | '/vote'
    | '/api/$'
    | '/api/distance'
    | '/api/search'
    | '/api/format/address'
    | '/api/geofence/check'
    | '/api/public/bulk-zip'
    | '/api/public/stats'
    | '/api/shipping/estimate'
    | '/api/travel/visa-requirements'
    | '/api/utils/anonymize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRoute
  StatusRoute: typeof StatusRoute
  VoteRoute: typeof VoteRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiDistanceRoute: typeof ApiDistanceRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiFormatAddressRoute: typeof ApiFormatAddressRoute
  ApiGeofenceCheckRoute: typeof ApiGeofenceCheckRoute
  ApiPublicBulkZipRoute: typeof ApiPublicBulkZipRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiShippingEstimateRoute: typeof ApiShippingEstimateRoute
  ApiTravelVisaRequirementsRoute: typeof ApiTravelVisaRequirementsRoute
  ApiUtilsAnonymizeRoute: typeof ApiUtilsAnonymizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/distance': {
      id: '/api/distance'
      path: '/api/distance'
      fullPath: '/api/distance'
      preLoaderRoute: typeof ApiDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/format/address': {
      id: '/api/format/address'
      path: '/api/format/address'
      fullPath: '/api/format/address'
      preLoaderRoute: typeof ApiFormatAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geofence/check': {
      id: '/api/geofence/check'
      path: '/api/geofence/check'
      fullPath: '/api/geofence/check'
      preLoaderRoute: typeof ApiGeofenceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bulk-zip': {
      id: '/api/public/bulk-zip'
      path: '/api/public/bulk-zip'
      fullPath: '/api/public/bulk-zip'
      preLoaderRoute: typeof ApiPublicBulkZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping/estimate': {
      id: '/api/shipping/estimate'
      path: '/api/shipping/estimate'
      fullPath: '/api/shipping/estimate'
      preLoaderRoute: typeof ApiShippingEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/visa-requirements': {
      id: '/api/travel/visa-requirements'
      path: '/api/travel/visa-requirements'
      fullPath: '/api/travel/visa-requirements'
      preLoaderRoute: typeof ApiTravelVisaRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/utils/anonymize': {
      id: '/api/utils/anonymize'
      path: '/api/utils/anonymize'
      fullPath: '/api/utils/anonymize'
      preLoaderRoute: typeof ApiUtilsAnonymizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReportRoute: ReportRoute,
  StatusRoute: StatusRoute,
  VoteRoute: VoteRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiDistanceRoute: ApiDistanceRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiFormatAddressRoute: ApiFormatAddressRoute,
  ApiGeofenceCheckRoute: ApiGeofenceCheckRoute,
  ApiPublicBulkZipRoute: ApiPublicBulkZipRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiShippingEstimateRoute: ApiShippingEstimateRoute,
  ApiTravelVisaRequirementsRoute: ApiTravelVisaRequirementsRoute,
  ApiUtilsAnonymizeRoute: ApiUtilsAnonymizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
